name: Bootbatch
pygments: true
lsi: false
auto: true
url: http://bootbatch.volumens.com
# this goes inside _config.yml. Change as required
navigation:
- text: Home
  url: index.html
- text: Docs
  url: docs/index.html
- text: About
  url: about/index.html


